tests, imsm: Fix unit inconsistency in tests error messages
Chunk size copied from sysfs should be divied by 1024 to compare with
expected chunk size.

Signed-off-by: Michal Zylowski <michal.zylowski@intel.com>
Signed-off-by: Jes Sorensen <jsorensen@fb.com>

diff --git a/tests/env-imsm-template b/tests/env-imsm-template
--- a/tests/env-imsm-template
+++ b/tests/env-imsm-template
@@ -30,7 +30,7 @@ imsm_check() {
         fi
         _chunk=`cat ${sysfs}/md/chunk_size`
         if [ $t_chunk -ne $((_chunk/1024)) ]; then
-            echo "**Error**: Chunk size mismatch - expected $t_chunk, actual $_chunk" >&2
+            echo "**Error**: Chunk size mismatch - expected $t_chunk, actual $(($_chunk/1024))" >&2
             err=$((err + 1))
         fi
         for i in `seq 0 $((t_num_disks - 1))`; do
